### ISSUE TITLE
IndexedTable(load(...)) gives an NDSparse instead of a Table

### ISSUE THREAD

**Issue by tcovert** [davidanthoff/CSVFiles.jl#15]
Is there a way to request a specific formulation of the `IndexedTable` type when reading in a CSV?  Right now it seems to default to the full `NDSparse` representation, in which the `n-1` leftmost columns are keys and the rightmost column is a value.  For my use cases, getting a plain IndexedTable with no primary key columns is more useful.

Note, this is not a show stopper.  This, for example, works fine
```
t = IndexedTable(load("file.csv"))
t = table(t)
```

**Comment by davidanthoff** [comment]
IndexedTables v0.4.2 should have added support for ``table(load("file.csv"))``.
