### ISSUE TITLE
Error when loading a remote URL CSV file

### ISSUE THREAD

**Issue by iscalprog** [davidanthoff/CSVFiles.jl#21]
First, would like to thank you for this amazing ecosystem of interoperable IO packages that you created. 

When loading a CSV file from the following European Central Bank URL 

http://sdw.ecb.europa.eu/quickviewexport.do?trans=N&start=&end=&SERIES_KEY=165.YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0&type=csv

using ```load("http://sdw.ecb.europa.eu/......")```, or ```load("http://sdw.ecb.europa.eu/...... , header_exists=false, skiplines_begin=5")```, one gets the following error:
```
ERROR: LoadError: 
SystemError: opening file http://sdw.ecb.europa.eu/quickviewexport.do?trans=N&start=&end=&SERIES_KEY=165.YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0&type=csv
:Invalid argument
```
The URL is valid, one can use (although being a much less attractive choice) ```Requests.get``` without error, so was expecting we could load this CSV file. Thank you very much for your time.

**Comment by davidanthoff** [comment]
The problem here is that ``load`` doesn't know what file type this is because there is no file extension in the URL. But, fear not, you can force the CSV loader to run in the following way:
````julia
load(File{format"CSV"}("http://sdw.ecb.europa.eu/quickviewexport.do?trans=N&start=&end=&SERIES_KEY=165.YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0&type=csv"), skiplines_begin=4)
````
I also had to add a ``skiplines_begin``, and then it worked on my system.
